In [1]:
import numpy as np
import pandas as pd

In [2]:
a = {
    "Name":["Tarun","Mahi","Likhil","Guptha","Rohit","Karthik"],
    "Age":[20,21,20,19,18,22],
    "Dep":["MIS","MIS","MIA","MIS","MIA","BEC"],
    "Roll":[22,32,43,23,13,43]
}

data_frame = pd.DataFrame(a)
print(data_frame)

      Name  Age  Dep  Roll
0    Tarun   20  MIS    22
1     Mahi   21  MIS    32
2   Likhil   20  MIA    43
3   Guptha   19  MIS    23
4    Rohit   18  MIA    13
5  Karthik   22  BEC    43


In [34]:
print(a["Name"])

['Tarun', 'Mahi', 'Likhil', 'Guptha', 'Rohit', 'Karthik']


In [3]:
data_frame.to_csv("Friends_Data.csv",index=False)

In [4]:
print(data_frame.head())

     Name  Age  Dep  Roll
0   Tarun   20  MIS    22
1    Mahi   21  MIS    32
2  Likhil   20  MIA    43
3  Guptha   19  MIS    23
4   Rohit   18  MIA    13


In [5]:
print(data_frame.tail())

      Name  Age  Dep  Roll
1     Mahi   21  MIS    32
2   Likhil   20  MIA    43
3   Guptha   19  MIS    23
4    Rohit   18  MIA    13
5  Karthik   22  BEC    43


In [6]:
print(data_frame.describe())

             Age       Roll
count   6.000000   6.000000
mean   20.000000  29.333333
std     1.414214  12.176480
min    18.000000  13.000000
25%    19.250000  22.250000
50%    20.000000  27.500000
75%    20.750000  40.250000
max    22.000000  43.000000


In [7]:
data1 = pd.read_csv("Friends_Data.csv")

In [8]:
print(data1)

      Name  Age  Dep  Roll
0    Tarun   20  MIS    22
1     Mahi   21  MIS    32
2   Likhil   20  MIA    43
3   Guptha   19  MIS    23
4    Rohit   18  MIA    13
5  Karthik   22  BEC    43


In [9]:
data1.index = [1,2,3,4,5,6]

In [10]:
print(data1)

      Name  Age  Dep  Roll
1    Tarun   20  MIS    22
2     Mahi   21  MIS    32
3   Likhil   20  MIA    43
4   Guptha   19  MIS    23
5    Rohit   18  MIA    13
6  Karthik   22  BEC    43


In [11]:
data2 = pd.DataFrame(np.random.rand(5,4))
data2.index = [1,2,3,4,5]

In [12]:
print(data2)

          0         1         2         3
1  0.974851  0.667705  0.732347  0.622953
2  0.461936  0.107970  0.878717  0.585966
3  0.410823  0.129110  0.619056  0.943020
4  0.725722  0.472756  0.804059  0.536935
5  0.001083  0.501163  0.903174  0.379495


In [13]:
data_array = data2.to_numpy()
print(data_array)
print(data_array.shape)

[[0.97485145 0.66770499 0.73234696 0.62295329]
 [0.46193612 0.10797044 0.87871662 0.58596609]
 [0.41082312 0.12910967 0.61905583 0.94302044]
 [0.72572152 0.4727565  0.80405854 0.5369347 ]
 [0.00108336 0.50116256 0.90317392 0.37949521]]
(5, 4)


In [14]:
print(data_array.T)

[[0.97485145 0.46193612 0.41082312 0.72572152 0.00108336]
 [0.66770499 0.10797044 0.12910967 0.4727565  0.50116256]
 [0.73234696 0.87871662 0.61905583 0.80405854 0.90317392]
 [0.62295329 0.58596609 0.94302044 0.5369347  0.37949521]]


In [15]:
print(data2.sort_index(axis=1,ascending = False))

          3         2         1         0
1  0.622953  0.732347  0.667705  0.974851
2  0.585966  0.878717  0.107970  0.461936
3  0.943020  0.619056  0.129110  0.410823
4  0.536935  0.804059  0.472756  0.725722
5  0.379495  0.903174  0.501163  0.001083


In [16]:
print(data1)

      Name  Age  Dep  Roll
1    Tarun   20  MIS    22
2     Mahi   21  MIS    32
3   Likhil   20  MIA    43
4   Guptha   19  MIS    23
5    Rohit   18  MIA    13
6  Karthik   22  BEC    43


In [17]:
print(data1.sort_index(axis=1,ascending = False))

   Roll     Name  Dep  Age
1    22    Tarun  MIS   20
2    32     Mahi  MIS   21
3    43   Likhil  MIA   20
4    23   Guptha  MIS   19
5    13    Rohit  MIA   18
6    43  Karthik  BEC   22


In [18]:
print(data1.sort_values(by=['Roll']))

      Name  Age  Dep  Roll
5    Rohit   18  MIA    13
1    Tarun   20  MIS    22
4   Guptha   19  MIS    23
2     Mahi   21  MIS    32
3   Likhil   20  MIA    43
6  Karthik   22  BEC    43


In [19]:
print(data1.sort_values(by=['Age','Roll']))

      Name  Age  Dep  Roll
5    Rohit   18  MIA    13
4   Guptha   19  MIS    23
1    Tarun   20  MIS    22
3   Likhil   20  MIA    43
2     Mahi   21  MIS    32
6  Karthik   22  BEC    43


In [20]:
print(data1)

      Name  Age  Dep  Roll
1    Tarun   20  MIS    22
2     Mahi   21  MIS    32
3   Likhil   20  MIA    43
4   Guptha   19  MIS    23
5    Rohit   18  MIA    13
6  Karthik   22  BEC    43


In [21]:
print(data1)

      Name  Age  Dep  Roll
1    Tarun   20  MIS    22
2     Mahi   21  MIS    32
3   Likhil   20  MIA    43
4   Guptha   19  MIS    23
5    Rohit   18  MIA    13
6  Karthik   22  BEC    43


In [22]:
hello = np.array([1,2,3,4,33,45])
data1['Hello'] = hello

In [23]:
print(data1)

      Name  Age  Dep  Roll  Hello
1    Tarun   20  MIS    22      1
2     Mahi   21  MIS    32      2
3   Likhil   20  MIA    43      3
4   Guptha   19  MIS    23      4
5    Rohit   18  MIA    13     33
6  Karthik   22  BEC    43     45


In [24]:
new_row = {
    "Name":["Vijay","Lakshmi"],
    "Age":[22,23],
    "Roll":[222,232],
    "Dep":["MIS","MIA"],
}

In [25]:
# data1 = data1.append(new_row,ignore_index=True)

data1.loc[6] = [1,2,3,4,5,6]

ValueError: Must have equal len keys and value when setting with an iterable

In [26]:
data1 = data1.drop("New Dict Col",axis = 1)

KeyError: "['New Dict Col'] not found in axis"

In [ ]:
data1 = data1.drop("Hello",axis=1)

In [ ]:
print(data1)

In [ ]:
data1.loc[:,["New"]] = [11,22,33,44,55,66]

In [27]:
print(data1)

      Name  Age  Dep  Roll  Hello
1    Tarun   20  MIS    22      1
2     Mahi   21  MIS    32      2
3   Likhil   20  MIA    43      3
4   Guptha   19  MIS    23      4
5    Rohit   18  MIA    13     33
6  Karthik   22  BEC    43     45


In [28]:
# print(data1.loc[(data1["Name"] == "Arun" and data1["Age"] == 20)])
print(data1.query('Name == "Arun" and Age == 20'))

Empty DataFrame
Columns: [Name, Age, Dep, Roll, Hello]
Index: []


In [29]:
print(data1.loc[(data1["Age"] < 20)])

     Name  Age  Dep  Roll  Hello
4  Guptha   19  MIS    23      4
5   Rohit   18  MIA    13     33


In [30]:
data1.loc[:,"new one"] = [1,2,3,4,5,5]

In [31]:
data1.drop("new one",axis=1,inplace=True)

In [32]:
print(data1)

      Name  Age  Dep  Roll  Hello
1    Tarun   20  MIS    22      1
2     Mahi   21  MIS    32      2
3   Likhil   20  MIA    43      3
4   Guptha   19  MIS    23      4
5    Rohit   18  MIA    13     33
6  Karthik   22  BEC    43     45


In [40]:
print(data1)

      Name  Age  Dep  Roll  Hello
1    Tarun   20  MIS    22      1
2     Mahi   21  MIS    32      2
3   Likhil   20  MIA    43      3
4   Guptha   19  MIS    23      4
5    Rohit   18  MIA    13     33
6  Karthik   22  BEC    43     45


In [38]:
data1.loc[:,"Name"] = a["Name"]

In [39]:
print(data1)

      Name  Age  Dep  Roll  Hello
1    Tarun   20  MIS    22      1
2     Mahi   21  MIS    32      2
3   Likhil   20  MIA    43      3
4   Guptha   19  MIS    23      4
5    Rohit   18  MIA    13     33
6  Karthik   22  BEC    43     45


In [41]:
data = pd.read_csv("heart-disease.csv")

In [43]:
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [50]:
data.loc[:,"sex"].mean(numeric_only = True)

0.6831683168316832

In [51]:
data.mean(numeric_only = True)

age          54.366337
sex           0.683168
cp            0.966997
trestbps    131.623762
chol        246.264026
fbs           0.148515
restecg       0.528053
thalach     149.646865
exang         0.326733
oldpeak       1.039604
slope         1.399340
ca            0.729373
thal          2.313531
target        0.544554
dtype: float64

In [54]:
data.sum()

age         16473.0
sex           207.0
cp            293.0
trestbps    39882.0
chol        74618.0
fbs            45.0
restecg       160.0
thalach     45343.0
exang          99.0
oldpeak       315.0
slope         424.0
ca            221.0
thal          701.0
target        165.0
dtype: float64

In [55]:
print(data1)

      Name  Age  Dep  Roll  Hello
1    Tarun   20  MIS    22      1
2     Mahi   21  MIS    32      2
3   Likhil   20  MIA    43      3
4   Guptha   19  MIS    23      4
5    Rohit   18  MIA    13     33
6  Karthik   22  BEC    43     45


In [62]:
print(data)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [70]:
print(data.loc[::-1])

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
302   57    0   1       130   236    0        0      174      0      0.0   
301   57    1   0       130   131    0        1      115      1      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
299   45    1   3       110   264    0        1      132      0      1.2   
298   57    0   0       140   241    0        1      123      1      0.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
4     57    0   0       120   354    0        1      163      1      0.6   
3     56    1   1       120   236    0        1      178      0      0.8   
2     41    0   1       130   204    0        0      172      0      1.4   
1     37    1   2       130   250    0        1      187      0      3.5   
0     63    1   3       145   233    1        0      150      0      2.3   

     slope  ca  thal  target  
302      1   1     2       0  
301      1   1     3     

In [71]:
print(data1)

       Name  Age  Dep  Roll  Hello
11    Tarun   20  MIS    22      1
22     Mahi   21  MIS    32      2
33   Likhil   20  MIA    43      3
44   Guptha   19  MIS    23      4
55    Rohit   18  MIA    13     33
66  Karthik   22  BEC    43     45


In [78]:
data1.rename(columns = {'Name':'Names'},inplace = True)

In [79]:
print(data1)

      Names  Age  Dep  Roll  Hello
11    Tarun   20  MIS    22      1
22     Mahi   21  MIS    32      2
33   Likhil   20  MIA    43      3
44   Guptha   19  MIS    23      4
55    Rohit   18  MIA    13     33
66  Karthik   22  BEC    43     45


In [140]:
series = pd.Series([1,92,34,4,55])
data1["hello"] = series

In [141]:
print(data1)

         Names   Age  Dep  Roll  Hello  hello
11       Tarun  20.0  MIS  22.0    1.0    NaN
22        Mahi  21.0  MIS  32.0    2.0    NaN
33      Likhil  20.0  MIA  43.0    3.0    NaN
44      Guptha  19.0  MIS  23.0    4.0    NaN
55       Rohit  18.0  MIA  13.0   33.0    NaN
66     Karthik  22.0  BEC  43.0   45.0    NaN
hello        1  92.0   34   4.0   55.0    NaN


In [144]:
data1['Names']=data1['Names'].str.upper()

In [145]:
print(data1)

         Names   Age  Dep  Roll  Hello  hello
11       TARUN  20.0  MIS  22.0    1.0    NaN
22        MAHI  21.0  MIS  32.0    2.0    NaN
33      LIKHIL  20.0  MIA  43.0    3.0    NaN
44      GUPTHA  19.0  MIS  23.0    4.0    NaN
55       ROHIT  18.0  MIA  13.0   33.0    NaN
66     KARTHIK  22.0  BEC  43.0   45.0    NaN
hello      NaN  92.0   34   4.0   55.0    NaN


In [120]:
data1.to_csv("Sample_data.csv")

In [132]:
data4 = pd.read_csv('Sample_data.csv')

In [133]:
data4

Unnamed: 0    Names  Age  Dep  Roll  Hello  hello
0         11    Tarun   20  MIS    22    1.0      1
1         22     Mahi   21  MIS    32    2.0     92
2         33   Likhil    0  MIA    43    NaN     34
3         44   Guptha   19  MIS    23    NaN      4
4         55      NaN   18  NaN     3    NaN      5
5         66  Karthik   22  BEC    43    NaN      5
6      hello        1   92   34     4   55.0     55

In [134]:
data4['Hello'].fillna(0.0,inplace = True)

In [135]:
data4

Unnamed: 0    Names  Age  Dep  Roll  Hello  hello
0         11    Tarun   20  MIS    22    1.0      1
1         22     Mahi   21  MIS    32    2.0     92
2         33   Likhil    0  MIA    43    0.0     34
3         44   Guptha   19  MIS    23    0.0      4
4         55      NaN   18  NaN     3    0.0      5
5         66  Karthik   22  BEC    43    0.0      5
6      hello        1   92   34     4   55.0     55